In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import kendalltau
from tqdm import tqdm
import datetime
from dateutil.parser import parse
import random

In [4]:
train=pd.read_csv(r"C:\Users\mercurial\Downloads\f_train_20180204.csv",encoding="gbk")
testa=pd.read_csv(r"C:\Users\mercurial\Downloads\f_test_a_20180204.csv",encoding="gbk")
sample=pd.read_csv(r"C:\Users\mercurial\Downloads\f_sample_20180204.csv",encoding="gbk")
answer=pd.read_csv(r"C:\Users\mercurial\Downloads\f_answer_a_20180306.csv",encoding="gbk",header=None)
testb=pd.read_csv(r"C:\Users\mercurial\Downloads\f_test_b_20180305.csv",encoding="gbk")

In [5]:
testb

id  SNP1  SNP2  SNP3  SNP4  SNP5  SNP6  SNP7  SNP8  SNP9  ...  SNP47  \
0    1201     1     2   3.0   2.0   2.0   1.0   3.0   2.0   1.0  ...    1.0   
1    1202     3     2   2.0   1.0   NaN   1.0   2.0   3.0   2.0  ...    NaN   
2    1203     2     1   3.0   2.0   3.0   1.0   3.0   2.0   1.0  ...    NaN   
3    1204     2     1   3.0   2.0   2.0   1.0   2.0   3.0   2.0  ...    2.0   
4    1205     2     2   NaN   1.0   2.0   1.0   3.0   NaN   NaN  ...    3.0   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...    ...   
195  1396     2     3   3.0   1.0   2.0   3.0   2.0   2.0   1.0  ...    NaN   
196  1397     1     3   2.0   2.0   2.0   1.0   2.0   3.0   2.0  ...    NaN   
197  1398     3     1   3.0   1.0   2.0   1.0   3.0   1.0   1.0  ...    3.0   
198  1399     3     3   3.0   1.0   3.0   1.0   2.0   3.0   2.0  ...    2.0   
199  1400     1     1   2.0   1.0   2.0   2.0   2.0   3.0   2.0  ...    NaN   

     SNP48  SNP49  SNP50  SNP51  SNP52  SNP53  SNP54  SNP55  ACEID  
0      3.0    NaN    NaN    2.0      2    1.0    2.0    2.0    3.0  
1      2.0    2.0    2.0    2.0      1    1.0    2.0    2.0    2.0  
2      2.0    NaN    1.0    NaN      2    NaN    2.0    2.0    2.0  
3      1.0    2.0    1.0    3.0      1    NaN    3.0    3.0    2.0  
4      3.0    1.0    1.0    1.0      1    1.0    3.0    3.0    2.0  
..     ...    ...    ...    ...    ...    ...    ...    ...    ...  
195    1.0    3.0    1.0    1.0      2    1.0    NaN    NaN    NaN  
196    2.0    1.0    1.0    2.0      1    1.0    NaN    NaN    NaN  
197    2.0    2.0    1.0    2.0      3    1.0    NaN    NaN    NaN  
198    2.0    2.0    1.0    1.0      1    1.0    NaN    NaN    NaN  
199    3.0    3.0    1.0    3.0      1    1.0    NaN    NaN    NaN  

[200 rows x 84 columns]

In [6]:
answer

0
0    1
1    1
2    1
3    1
4    1
..  ..
195  1
196  1
197  0
198  0
199  0

[200 rows x 1 columns]

In [7]:
testa["label"]=answer

In [8]:
testa

id  SNP1  SNP2  SNP3  SNP4  SNP5  SNP6  SNP7  SNP8  SNP9  ...  SNP48  \
0    1001   2.0     2   3.0   2.0   2.0     1     2     3     2  ...    3.0   
1    1002   2.0     3   3.0   1.0   3.0     1     2     2     1  ...    2.0   
2    1003   3.0     3   2.0   1.0   1.0     1     3     3     2  ...    2.0   
3    1004   2.0     2   3.0   1.0   2.0     2     3     2     1  ...    1.0   
4    1005   2.0     2   3.0   2.0   2.0     1     3     3     2  ...    3.0   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...    ...   
195  1196   2.0     2   3.0   1.0   1.0     2     2     1     1  ...    2.0   
196  1197   3.0     2   3.0   1.0   3.0     3     2     3     2  ...    1.0   
197  1198   2.0     2   3.0   1.0   1.0     1     3     2     1  ...    3.0   
198  1199   2.0     3   3.0   1.0   3.0     3     2     1     1  ...    2.0   
199  1200   3.0     2   3.0   1.0   NaN     2     2     3     2  ...    2.0   

     SNP49  SNP50  SNP51  SNP52  SNP53  SNP54  SNP55  ACEID  label  
0      3.0    2.0    3.0      1    1.0    1.0    1.0    2.0      1  
1      NaN    1.0    1.0      2    1.0    2.0    2.0    3.0      1  
2      2.0    1.0    2.0      1    1.0    2.0    2.0    3.0      1  
3      2.0    1.0    2.0      1    1.0    2.0    2.0    2.0      1  
4      1.0    1.0    3.0      1    1.0    1.0    1.0    3.0      1  
..     ...    ...    ...    ...    ...    ...    ...    ...    ...  
195    1.0    2.0    1.0      1    1.0    NaN    NaN    NaN      1  
196    2.0    1.0    2.0      1    1.0    NaN    NaN    NaN      1  
197    3.0    2.0    2.0      1    1.0    NaN    NaN    NaN      0  
198    1.0    1.0    1.0      2    1.0    NaN    NaN    NaN      0  
199    1.0    3.0    1.0      2    1.0    NaN    NaN    NaN      0  

[200 rows x 85 columns]

In [9]:
train=pd.concat([train,testa])

In [10]:
train

id  SNP1  SNP2  SNP3  SNP4  SNP5  SNP6  SNP7  SNP8  SNP9  ...  SNP48  \
0       1   2.0     1   NaN   2.0   3.0   1.0   3.0   3.0   2.0  ...    2.0   
1       2   3.0     2   3.0   2.0   2.0   2.0   3.0   3.0   2.0  ...    1.0   
2       3   1.0     1   3.0   1.0   3.0   2.0   3.0   3.0   2.0  ...    3.0   
3       4   1.0     3   3.0   1.0   NaN   1.0   3.0   1.0   1.0  ...    1.0   
4       5   1.0     2   3.0   2.0   2.0   1.0   2.0   2.0   1.0  ...    3.0   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...    ...   
195  1196   2.0     2   3.0   1.0   1.0   2.0   2.0   1.0   1.0  ...    2.0   
196  1197   3.0     2   3.0   1.0   3.0   3.0   2.0   3.0   2.0  ...    1.0   
197  1198   2.0     2   3.0   1.0   1.0   1.0   3.0   2.0   1.0  ...    3.0   
198  1199   2.0     3   3.0   1.0   3.0   3.0   2.0   1.0   1.0  ...    2.0   
199  1200   3.0     2   3.0   1.0   NaN   2.0   2.0   3.0   2.0  ...    2.0   

     SNP49  SNP50  SNP51  SNP52  SNP53  SNP54  SNP55  ACEID  label  
0      2.0    1.0    2.0    1.0    1.0    3.0    3.0    1.0      1  
1      3.0    1.0    1.0    2.0    1.0    2.0    2.0    3.0      0  
2      3.0    2.0    2.0    1.0    1.0    1.0    1.0    2.0      1  
3      3.0    1.0    2.0    1.0    1.0    2.0    2.0    3.0      1  
4      1.0    2.0    2.0    1.0    1.0    2.0    2.0    3.0      0  
..     ...    ...    ...    ...    ...    ...    ...    ...    ...  
195    1.0    2.0    1.0    1.0    1.0    NaN    NaN    NaN      1  
196    2.0    1.0    2.0    1.0    1.0    NaN    NaN    NaN      1  
197    3.0    2.0    2.0    1.0    1.0    NaN    NaN    NaN      0  
198    1.0    1.0    1.0    2.0    1.0    NaN    NaN    NaN      0  
199    1.0    3.0    1.0    2.0    1.0    NaN    NaN    NaN      0  

[1200 rows x 85 columns]

In [11]:
float_col=[]
for _ in train.columns:
    if train[_].values.dtype!="O":
        float_col.append(_)

In [12]:
train.shape

(1200, 85)

In [ ]:
float_col

In [ ]:
o_col=[]
for _ in train.columns:
    if train[_].values.dtype=="O":
        o_col.append(_)

In [ ]:
o_col

In [ ]:
def insight(_):
    print(_,"的统计量分析")
    print(train[_].describe())
    null_sum=train[_].isnull().values.sum()
    if null_sum==0:
        print("没有缺失值")
    else:
        print("缺失值数量为:",null_sum,"缺失值比例为:" , null_sum/train.count().max())
    print("相关性：",train[_].corr(train["label"]))
    if len(train[_].unique())<10:
        print("离散变量:",train[_].groupby(train[_]).count())
    else:
        print("连续变量")
    plt.plot(train[_],train["label"],"o")
    plt.title("train")
    plt.show()
    sns.jointplot(train[_], train["label"], kind="hex", stat_func=kendalltau, color="#4CB391")
    plt.show()
    plt.rcParams['font.sans-serif'] = ['SimHei']
    plt.rcParams['axes.unicode_minus'] = False
    plt.figure(1, figsize=(5, 5))#可设定图像大小
    p = train[[_]].boxplot() 
    plt.show()

In [ ]:
for _ in float_col:
    insight(_)

In [ ]:
#train.drop(["SNP21","SNP22","SNP23","RBP4","分娩时","SNP54","SNP55","ACEID"],axis=1,inplace=True)
#testa.drop(["SNP21","SNP22","SNP23","RBP4","分娩时","SNP54","SNP55","ACEID"],axis=1,inplace=True)

In [ ]:
"""
尝试one-hot发现处理后的数据集特征数不一样
def to_str(df):
    for _ in df.drop(["id","label",'RBP4','年龄','孕次','产次','身高','孕前体重','BMI分类','孕前BMI','收缩压','舒张压','分娩时',
                      '糖筛孕周','VAR00007','wbc','ALT','AST','Cr','BUN','CHO','TG','HDLC','LDLC','ApoA1','ApoB','Lpa','hsCRP'
                     ],axis=1).columns:
        df[_]=df[_].apply(lambda x : str(x))
to_str(train)
testa["label"]=1
to_str(testa)
train=pd.get_dummies(train)
testa=pd.get_dummies(testa)
"""

In [ ]:
"""
def fillna(df):
    df.fillna(-999,axis=1,inplace=True)
    fillna(train)
    fillna(testa)
"""

In [ ]:
#暴力特征之加减乘除log指数多项式
def make_feature(df):
    #暴力特征
    col_1=df.drop(["id","label"],axis=1).columns.tolist()
    col_2=df.drop(["id","label"],axis=1).columns.tolist()
    for _ in tqdm(col_1):
        df[_,"2"]=df[_]*df[_]
        col_2.remove(_)
        for __ in col_2:
            #df[_,"+",__]=df[_]+df[__]
            #df[_,"-",__]=df[_]-df[__]
            df[_,"*",__]=df[_]*df[__]
            df[_,"/",__]=df[_]/df[__]
    #提取log指数特征
    #col_list=df.drop(["id","label"],axis=1).columns.tolist()
    #for _ in tqdm(col_list):
    #    df["log",_]=np.log(df[_])
    #    df[_,"2"]=df[_]*df[_]

In [ ]:
make_feature(train)
testb["label"]=1
make_feature(testb)
testb.drop("label",axis=1,inplace=True)

In [ ]:
print(train.shape,testb.shape)

In [ ]:
import xgboost as xgb
import lightgbm as lgb
from catboost import CatBoostClassifier
from sklearn import cross_validation, metrics

In [35]:
lgb_model=lgb.LGBMClassifier(objective="binary",n_estimators=300,learning_rate =0.08,max_depth=3)
lgb_model.fit(train.drop(["id","label"],axis=1), train["label"])
lgb_pred=lgb_model.predict(testb.drop("id",axis=1))

In [36]:
cat_model=CatBoostClassifier(iterations=100, learning_rate=0.1, depth=4, loss_function='Logloss',eval_metric='F1')
cat_model.fit(train.drop(["id","label"],axis=1), train["label"])
cat_pred=cat_model.predict(testb.drop("id",axis=1))

0:	learn: 0.6568627	total: 333ms	remaining: 33s
1:	learn: 0.6587771	total: 536ms	remaining: 26.3s
2:	learn: 0.6558376	total: 715ms	remaining: 23.1s
3:	learn: 0.6613226	total: 901ms	remaining: 21.6s
4:	learn: 0.6772592	total: 1.08s	remaining: 20.6s
5:	learn: 0.6786070	total: 1.27s	remaining: 19.9s
6:	learn: 0.6825871	total: 1.46s	remaining: 19.3s
7:	learn: 0.6861167	total: 1.64s	remaining: 18.9s
8:	learn: 0.6906907	total: 1.82s	remaining: 18.4s
9:	learn: 0.7030785	total: 2.01s	remaining: 18.1s
10:	learn: 0.6926927	total: 2.2s	remaining: 17.8s
11:	learn: 0.7085828	total: 2.38s	remaining: 17.5s
12:	learn: 0.7211155	total: 2.57s	remaining: 17.2s
13:	learn: 0.7353816	total: 2.75s	remaining: 16.9s
14:	learn: 0.7418398	total: 2.94s	remaining: 16.7s
15:	learn: 0.7440476	total: 3.13s	remaining: 16.4s
16:	learn: 0.7477745	total: 3.3s	remaining: 16.1s
17:	learn: 0.7490119	total: 3.48s	remaining: 15.8s
18:	learn: 0.7460630	total: 3.67s	remaining: 15.6s
19:	learn: 0.7570732	total: 3.85s	remaining: 

In [37]:
xgb_model=xgb.XGBClassifier(objective='binary:logistic',learning_rate =0.05,max_depth=5,n_estimators=100)
xgb_model.fit(train.drop(["id","label"],axis=1), train["label"])
xgb_pred=xgb_model.predict(testb.drop("id",axis=1))

In [80]:
xgb_pred

array([0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0], dtype=int64)

In [81]:
lgb_pred

array([0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0], dtype=int64)

In [82]:
cat_pred

array([ 0.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  1.,
        0.,  0.,  0.,  0.,  1.,  1.,  0.,  1.,  1.,  0.,  1.,  1.,  0.,
        0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  1.,
        0.,  0.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  1.,  1.,
        0.,  1.,  0.,  0.,  0.,  1.,  1.,  1.,  0.,  1.,  0.,  0.,  1.,
        1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,
        1.,  1.,  1.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,
        0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,
        0.,  1.,  0.,  1.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,
        0.,  1.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  1.,
        1.,  1.,  1.,  0.,  1.,  0.,  0.,  1.,  0.,  1.,  1.,  1.,  0.,
        1.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,
        0.,  0.,  1.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,
        0.,  1.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0

In [84]:
pred=cat_pred+xgb_pred+lgb_pred

In [85]:
pred

array([ 0.,  2.,  0.,  0.,  3.,  1.,  2.,  0.,  0.,  3.,  0.,  0.,  2.,
        0.,  0.,  0.,  0.,  3.,  3.,  0.,  1.,  3.,  0.,  3.,  3.,  0.,
        0.,  3.,  0.,  0.,  2.,  0.,  0.,  3.,  0.,  0.,  1.,  2.,  3.,
        0.,  0.,  0.,  0.,  0.,  3.,  0.,  3.,  0.,  0.,  1.,  3.,  3.,
        0.,  3.,  0.,  1.,  0.,  3.,  1.,  3.,  0.,  3.,  0.,  1.,  3.,
        3.,  0.,  0.,  1.,  2.,  0.,  0.,  2.,  3.,  0.,  0.,  0.,  0.,
        1.,  3.,  1.,  1.,  3.,  3.,  0.,  1.,  2.,  0.,  3.,  0.,  0.,
        0.,  0.,  3.,  0.,  0.,  3.,  0.,  0.,  0.,  0.,  2.,  3.,  1.,
        0.,  3.,  0.,  1.,  0.,  0.,  3.,  2.,  1.,  3.,  3.,  0.,  0.,
        0.,  3.,  3.,  0.,  3.,  0.,  0.,  0.,  0.,  2.,  3.,  0.,  1.,
        2.,  3.,  3.,  1.,  3.,  0.,  0.,  3.,  0.,  1.,  3.,  3.,  0.,
        2.,  3.,  0.,  0.,  2.,  0.,  0.,  0.,  0.,  0.,  3.,  3.,  3.,
        0.,  0.,  3.,  0.,  0.,  3.,  3.,  2.,  0.,  0.,  2.,  3.,  3.,
        1.,  1.,  0.,  3.,  0.,  1.,  0.,  1.,  0.,  3.,  0.,  0

In [86]:
preds=pd.DataFrame(pred)

In [88]:
preds[0][preds[0]<=1]=0
preds[0][preds[0]>1]=1

In [91]:
preds.to_csv("D:/算法大赛/天池糖尿病预测/复赛/pred_final.csv",header=None,index=None)